-- Shared DSX defaults used by both GE Lua and vehicle Lua
return {
    VERSION = "3.0",
    DSX_IP = "127.0.0.1",
    DSX_PORT = 6969,
    CONTROLLER_INDEX = 0,
    ADAPTIVE_TRIGGERS_ENABLED = true,
    TRIGGER_EFFECT = {
        ABS_STRENGTH = 7,
        SLIP_STRENGTH = 7,
        SLIP_SENSITIVITY = 1,
        ABS_FREQUENCY = 10,
        SLIP_FREQUENCY = 30,
    },
    GEAR_LEDS_ENABLED = true,
    TURN_SIGNALS_ENABLED = true,
    TRIGGER_FORCE = {
        NOT_RUNNING = 8,
        RUNNING = 1,
    },
    REV_LIMITER_CUT_TIME = {
        DEFAULT = 100,
        MIN = 30,
        MAX = 200,
    },
    LED_CONFIG = {
        ENABLED = true,
        BRIGHTNESS = 1,
        RPM_START = 0,
        REV_LIMITER_ENABLED = true,
        RPM_HUE_FACTOR = 1.2,
        RPM_HUE_SCALE = 1.3,
        RPM_CLAMP_LOW = 0,
        RPM_CLAMP_HIGH = 0.33,
        TARGET_RPM_DECREMENT_OFF = 0.06,
        TARGET_RPM_DECREMENT_ON = 0.053,
        TURN_SIGNAL_COLOR = vec3(255, 200, 0),
    },
    STALL_LED_CONFIG = {
        ENABLED = true,
        FLASH_INTERVAL_MS = 500,
        RGB_ON = vec3(255, 255, 255),
        RGB_OFF = vec3(0, 0, 0),
    },
    CHECK_ENGINE_LED_CONFIG = {
        ENABLED = true,
        FADE_INTERVAL_MS = 750,
        RGB_MAX = vec3(255, 0, 0),
        RGB_MIN = vec3(0, 0, 0),
    },
    ND_RGB = vec3(0, 64, 128),
    ND_PLAYER_LED = {
        light1 = false,
        light2 = false,
        light3 = true,
        light4 = false,
        light5 = false,
    },
    NE_RGB = vec3(128, 0, 0),
    NE_PLAYER_LED = {
        light1 = false,
        light2 = false,
        light3 = false,
        light4 = false,
        light5 = false,
    },
    TIMER_MAX = 36000,
    MAX_RETRIES = 3,
    TEMPERATURE = {
        ENABLED = true,
        TEMP_WARNING = 115,
        TEMP_PULSE = 108,
    },
    NETWORK = {
        CACHE_STATE = true,
        RESYNC_INTERVAL = 1,
        MIN_PACKET_INTERVAL = 1 / 60,
        RETRY_COOLDOWN = 0.1,
    },
    LOW_FUEL_CONFIG = {
        ENABLED = true,
        FLASH_INTERVAL_MS = 500,
    },
}
